name: Build Xray for ImmortalWrt (mediatek/filogic)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build Xray (mediatek/filogic)

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libncurses5-dev libssl-dev python3 \
            python3-distutils unzip wget python3-setuptools rsync subversion \
            swig time xsltproc zlib1g-dev xz-utils zstd

      - name: Download ImmortalWrt SDK
        run: |
          SDK_URL="https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
          wget $SDK_URL -O sdk.tar.zst
          mkdir sdk && tar --use-compress-program=unzstd -xvf sdk.tar.zst -C sdk --strip-components=1

      - name: Add Xray feed
        run: |
          echo "src-git xray https://github.com/yichya/openwrt-xray.git" >> sdk/feeds.conf.default
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure Package Selection
        run: |
          cd sdk
          # Enable xray-core & luci-app-xray
          echo "CONFIG_PACKAGE_xray-core=m" >> .config
          echo "CONFIG_PACKAGE_luci-app-xray=m" >> .config
          make defconfig

      - name: Compile Xray Packages
        run: |
          cd sdk
          make package/xray-core/{clean,compile} -j$(nproc) V=s
          make package/luci-app-xray/{clean,compile} -j$(nproc) V=s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xray-ipk-filgic
          path: |
            sdk/bin/packages/*/base/xray-core_*.ipk
            sdk/bin/packages/*/luci/luci-app-xray_*.ipk

  release:
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: xray-ipk-filgic
          path: release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "xray-filgic-$(date +'%Y%m%d')"
          name: "Xray ImmortalWrt (filogic) $(date +'%Y-%m-%d')"
          draft: false
          prerelease: false
          files: release/*.ipk
