name: Build luci-app-xray for GL-MT6000 (Filogic)

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ "main" ] # 推送到 main 分支时触发
  schedule:
    - cron: '0 10 * * 1' # 每周一早上10点(UTC)自动编译一次

env:
  # 使用您提供的通用链接，避免版本号过期问题
  SDK_URL: https://mirror-03.infra.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
  # OpenWrt 软件源配置
  FEEDS_CONF: |
    src-git packages https://git.openwrt.org/feed/packages.git
    src-git luci https://git.openwrt.org/project/luci.git
    src-git routing https://git.openwrt.org/feed/routing.git
    src-git telephony https://git.openwrt.org/feed/telephony.git

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Install Zstd compression tool
      run: sudo apt-get update && sudo apt-get install -y zstd

    - name: Download and extract OpenWrt SDK
      run: |
        wget ${{ env.SDK_URL }} -O openwrt-sdk.tar.zst
        tar -I zstd -xf openwrt-sdk.tar.zst --strip-components=1
        rm openwrt-sdk.tar.zst

    - name: Setup feeds configuration
      run: echo "${{ env.FEEDS_CONF }}" > feeds.conf

    - name: Update and install all feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-app-xray source
      run: |
        git clone https://github.com/yichya/luci-app-xray.git package/luci-app-xray

    - name: Prepare configuration
      run: |
        echo "CONFIG_PACKAGE_luci-app-xray=y" >> .config
        make defconfig

    - name: Compile luci-app-xray package
      run: |
        make package/luci-app-xray/compile V=s

    - name: List built packages
      run: ls -la bin/packages/aarch64_cortex-a53/

    - name: Upload IPK files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-ipks-for-mt6000
        path: bin/packages/aarch64_cortex-a53/
        retention-days: 7

    - name: Upload compilation log
      if: always() # 即使编译失败也上传日志
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
        retention-days: 7
