name: Build luci-app-xray

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf immortalwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          mv immortalwrt-sdk-*/ sdk

      - name: Clone luci-app-xray only
        run: |
          cd sdk/package
          git clone https://github.com/yichya/openwrt-xray.git
          # 只需要 luci-app-xray，其他目录可以删掉
          find openwrt-xray -maxdepth 1 -type d ! -name luci-app-xray ! -name openwrt-xray -exec rm -rf {} +

      - name: Configure minimal build
        run: |
          cd sdk
          rm -f .config
          cat >> .config <<EOF
          CONFIG_TARGET_mediatek=y
          CONFIG_TARGET_mediatek_filogic=y
          CONFIG_TARGET_mediatek_filogic_generic=y
          CONFIG_PACKAGE_luci-app-xray=m
          EOF
          make defconfig

      - name: Build luci-app-xray
        run: |
          cd sdk
          make package/openwrt-xray/luci-app-xray/compile -j$(nproc) V=s

      - name: Collect artifacts
        run: |
          mkdir -p output
          find sdk/bin/packages/ -type f -name "*luci-app-xray*.ipk" -exec cp {} output/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-xray-ipk
          path: output/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*
