name: Build luci-app-xray for GL-MT6000 (Filogic)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  SDK_URL: https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
  FEEDS_CONF: |
    src-git packages https://git.openwrt.org/feed/packages.git
    src-git luci https://git.openwrt.org/project/luci.git
    src-git routing https://git.openwrt.org/feed/routing.git
    src-git telephony https://git.openwrt.org/feed/telephony.git

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zstd build-essential libncurses5-dev libncursesw5-dev \
        zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3

    - name: Download and extract OpenWrt SDK
      run: |
        wget ${{ env.SDK_URL }} -O openwrt-sdk.tar.zst
        tar -I zstd -xf openwrt-sdk.tar.zst --strip-components=1
        rm openwrt-sdk.tar.zst

    - name: Setup feeds configuration
      run: echo "${{ env.FEEDS_CONF }}" > feeds.conf

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-app-xray source
      run: |
        rm -rf package/luci-app-xray
        git clone https://github.com/yichya/luci-app-xray.git package/luci-app-xray

    - name: Prepare the build environment
      run: |
        # 创建符号链接确保编译系统能找到包
        ln -sf $(pwd)/package/luci-app-xray $(pwd)/package/feeds/packages/luci-app-xray || true
        ln -sf $(pwd)/package/luci-app-xray $(pwd)/package/feeds/luci/luci-app-xray || true
        
        # 确保包索引已更新
        make package/index

    - name: Check if package is detected
      run: |
        echo "Checking if luci-app-xray is detected by the build system..."
        make package/luci-app-xray/check V=s || true
        make package/luci-app-xray/prepare V=s || true

    - name: Compile luci-app-xray package
      run: |
        # 首先尝试直接编译
        make package/luci-app-xray/compile V=s || \
        # 如果失败，尝试先编译依赖
        (make tools/install && make toolchain/install && make package/luci-app-xray/compile V=s)

    - name: List built packages
      run: |
        find bin/ -name "*.ipk" | grep -E "(xray|luci-app-xray)" || true
        ls -la bin/packages/ || true

    - name: Upload IPK files as artifact
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-ipks-for-mt6000
        path: |
          bin/packages/*/base/
          bin/packages/*/luci/
          bin/packages/*/packages/
        retention-days: 7

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: |
          logs/
          build.log
        retention-days: 7
